checks:
    php: true
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
filter:
    excluded_paths:
        - "vendor/*"
        - "tests/*"
    paths:
        - "src/*"
tools:
    php_analyzer: true
    php_changetracking: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
    php_cpd: true
    php_mess_detector: true
    php_pdepend: true
    php_sim: true
build:
    dependencies:
        before:
            - "sudo composer self-update"
        override:
            - "composer install --no-interaction --prefer-dist"
    tests:
        override:
            -
                command: './vendor/bin/phpunit -c phpunit.xml --coverage-clover=clover.xml'
                coverage:
                    file: 'clover.xml'
                    format: 'php-clover'
